# Generated by Django 2.0.7 on 2019-01-25 09:58

from django.utils import timezone

from django.db import migrations, models

from refreshtoken.settings import api_settings as jwt_refresh_settings


class Migration(migrations.Migration):

    dependencies = [
        ('refreshtoken', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='refreshtoken',
            name='expires',
            field=models.DateTimeField(
                default=timezone.now() +
                jwt_refresh_settings.JWT_REFRESH_TOKEN_EXPIRATION_DELTA
            ),
            preserve_default=False,
        ),
    ]
