# Generated by Django 2.0.7 on 2019-01-25 09:58

from django.utils import timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('refreshtoken', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='refreshtoken',
            name='expires',
            field=models.DateTimeField(
                default=timezone.now() + timezone.timedelta(days=182.5)
            ),
            preserve_default=False,
        ),
    ]
